// examples/vue/src/App.vue
<script setup lang="ts">
import { isApiError } from "@apixa/core";
import { onMounted, ref } from "vue";
import { api, type User } from "./api";

const users = ref<User[]>([]);
const name = ref("");
const email = ref("");
const error = ref<string | null>(null);
const loading = ref(true);

async function load() {
  error.value = null;
  try {
    users.value = await api.users.getAll();
  } catch (err) {
    error.value = isApiError(err)
      ? `${err.name}: ${err.message}. Start the FastAPI backend on :8787.`
      : "Failed to load users";
  } finally {
    loading.value = false;
  }
}

async function createUser() {
  error.value = null;
  try {
    await api.users.create({ name: name.value, email: email.value });
    name.value = "";
    email.value = "";
    await load();
  } catch (err) {
    error.value = isApiError(err) ? err.message : "Create failed";
  }
}

async function remove(id: string) {
  error.value = null;
  try {
    await api.users.delete(id);
    await load();
  } catch (err) {
    error.value = isApiError(err) ? err.message : "Delete failed";
  }
}

onMounted(() => {
  void load();
});
</script>

<template>
  <main>
    <p class="eyebrow">Apixa · Vue</p>
    <h1>Typed client in Vue 3</h1>
    <p class="lede">Uses <code>defineApi</code> from <code>@apixa/core</code>.</p>

    <p v-if="error" class="error">{{ error }}</p>
    <p v-if="loading">Loading…</p>

    <ul>
      <li v-for="user in users" :key="user.id">
        <div>
          <strong>{{ user.name }}</strong>
          <span>{{ user.email }} · {{ user.id }}</span>
        </div>
        <button type="button" @click="remove(user.id)">Delete</button>
      </li>
    </ul>

    <form @submit.prevent="createUser">
      <input v-model="name" placeholder="Name" required />
      <input v-model="email" type="email" placeholder="Email" required />
      <button type="submit">Create</button>
    </form>
  </main>
</template>

// examples/react-vite/src/App.tsx
import { isApiError } from "@apixa/core";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, type User } from "./api";

export function App() {
  const [users, setUsers] = useState<User[]>([]);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setError(null);
    try {
      setUsers(await api.users.getAll());
    } catch (err) {
      setError(
        isApiError(err)
          ? `${err.name}: ${err.message}. Start the FastAPI backend on :8787.`
          : "Failed to load users",
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function onCreate(event: FormEvent) {
    event.preventDefault();
    setError(null);
    try {
      await api.users.create({ name, email });
      setName("");
      setEmail("");
      await load();
    } catch (err) {
      setError(isApiError(err) ? err.message : "Create failed");
    }
  }

  async function onDelete(id: string) {
    setError(null);
    try {
      await api.users.delete(id);
      await load();
    } catch (err) {
      setError(isApiError(err) ? err.message : "Delete failed");
    }
  }

  return (
    <main>
      <p className="eyebrow">Apixa · React + Vite</p>
      <h1>Typed client in a Vite React app</h1>
      <p className="lede">Same <code>defineApi</code> client as Next — browser-only here.</p>

      {error ? <p className="error">{error}</p> : null}
      {loading ? <p>Loading…</p> : null}

      <ul>
        {users.map((user) => (
          <li key={user.id}>
            <div>
              <strong>{user.name}</strong>
              <span>
                {user.email} · {user.id}
              </span>
            </div>
            <button type="button" onClick={() => void onDelete(user.id)}>
              Delete
            </button>
          </li>
        ))}
      </ul>

      <form onSubmit={onCreate}>
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" required />
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="Email"
          required
        />
        <button type="submit">Create</button>
      </form>
    </main>
  );
}
